language: ruby
rvm: 2.5.1

before_install:
  - gem install bundler
  - bundle install --path vendor/bundle --full-index

script:
  - rm -rf _site
  - JEKYLL_ENV=production bundle exec jekyll build --drafts --future
  - bundle exec htmlproofer --assume-extension --disable-external --url-ignore "#,#fn:1" --alt-ignore '/.*/' ./_site


branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
